config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"

  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates :name, presence: true
    validates :calories, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  #Index shows all foods with the same userid as the current user
  def index
    @current_user_id = current_user.id
    @foods = Food.where(userid: @current_user_id)
  end

  #shows individual foods based on food id (can be made more secure by ensuring the user id is the same aswell)
  def show
    @food = Food.find(params[:id])
    #if @food.userid != @current_user_id #checks if food user is trying to view is connected to users id
    #  redirect_to root_path #TODO: Show error message that food doesnt exisit
    #else
    #end
  end

  def new
    @food = Food.new
  end

  #Creates a new food using the form submitted by user
  def create
    @food = Food.new(name: params[:food][:name], calories: params[:food][:calories], userid: current_user.id)

    if @food.save
      redirect_to @food
    else
      render :new
    end
  end

  #edits food object based on info submited in the form by the user
  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])

    if @food.update(food_params)
      redirect_to @food
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to root_path
  end

  private
    def food_params
      params.require(:food).permit(:name, :calories, :userid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
    def calorieSum(foods)
        totalCals = 0
            foods.each do |food|
                totalCals = totalCals + food.calories
            end
        return totalCals
    end
end

app/views/foods/_form.html.erb
<%= form_with model: food do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_area :name %>
        <% food.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :calories %><br>
        <%= form.text_area :calories %>
        <% food.errors.full_messages_for(:calories).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
            
    <div>
        <%= form.submit %>
    </div>

    <div>
        <%= link_to "Home", foods_path %>
<% end %>

app/views/foods/edit.html.erb
<h1> Edit Food </h1>

<%= render "form", food: @food %>

app/views/foods/index.html.erb
<!DOCTYPE html>
    <head>
        <title> Foods </title>
    </head>

    <div>
    <header>

        <%= button_to "logout", destroy_user_session_path, method: :delete, form_class: 'btn btn-logout' %>
    </header>
    </div>
    <body>
        <h1> Foods </h1>
        <p>
        <div>
            <ul class='foodList'>
                <% @foods.each do |food| %>
                        <li><%= link_to food.name, food, class: "btn btn-food" %></li><li>Calories: <%= food.calories %></li>
                <% end %>
            </ul>
        </div>
            Total Calories: <%= calorieSum(@foods) %></p>
            <%= link_to "Add New Food", new_food_path, class: "btn btn-new" %>
    </body>

    <footer>
        <p>Created By: Evan Hope</p>
        <p>Email: hopee1@tcnj.edu</p>
        <!-- <a class='footerLink' href="hopee1@tcnj.edu">hopee1@tcnj.edu</a> -->
    </footer>
</html>

app/views/foods/new.html.erb
<h1> New Food </h1>

<%= render "form", food: @food %>

app/views/foods/show.html.erb
<!DOCTYPE html>
    <head>
        <title> Food Details </title>
    </head>

    <h1><%= @food.name %></h1>

    <body>
        <p>Calories: <%= @food.calories %></p>
        <ul class='showOptions'>
            <li><%= link_to "Home", foods_path, class: "btn btn-show"%></li>
            <li><%= link_to "Edit", edit_food_path(@food), class: "btn btn-show" %></li>
            <li><%= link_to "Destroy", food_path(@food),
                            method: :delete,
                            data: { confirm: "Are you sure?" } , class: "btn btn-show" %></li>
        </ul>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalorieCounter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>